import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AppHeader from "@/components/header";
import "./globals.css";
import AppFooter from "@/components/footer";
import "bootstrap/dist/css/bootstrap.min.css";
import { UserProvider } from "./context/userContext";
import Notifi from "@/components/notify/notify";
import OpenNotifi from "@/components/notify/openNotify";
import { Button } from "react-bootstrap";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Vexere",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>{children} 
          <OpenNotifi />
        </UserProvider>
      </body>
    </html>
  );

}
