import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import AppHeader from '@/components/header';
import AppFooter from '@/components/footer';
import 'bootstrap/dist/css/bootstrap.min.css';
import { UserContext, UserProvider } from '../context/userContext';
import OpenNotifi from '@/components/notify/openNotify';
import { useContext } from 'react';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    // const { setUser } = useContext(UserContext);
    // const user = localStorage.getItem('user')
    // if(user) {
    //     setUser(JSON.parse(user))
    // }
    return (
        <html lang="en">
            {/* <p>11111111111</p> */}
            <body className={inter.className}>
                <AppHeader />
                {children}
            </body>
            <AppFooter />
        </html>
    );
}
